### ISSUE TITLE
Impossible to specify target for svgDrawer as element

### ISSUE THREAD

**Issue by au1985** [reymond-group/smilesDrawer#127]
I am developing a Vue.js wrapper for smilesDrawer. It is not always possible to get element ids in reactive frameworks, at least in Vue, but it is possible to get true HTML element.

smilesDrawer allows to specify target either by id, or by passing an element as target, although this does not seem to be documented. But svgDrawer only accepts string as an element id.

I think this should be fixed to facilitate integration of smilesDrawer into reactive apps.

**Comment by swamidass** [comment]
This should be fixed now.
