### ISSUE TITLE
Some Smiles rendered wrongly

### ISSUE THREAD

**Issue by Valen-C12** [reymond-group/smilesDrawer#166]
smiles: `Cn1nc(NS(C)(=O)=O)c2cc(Cl)c(COc3ccc(Cl)c(Cl)c3)cc21`
render with smilesDrawer:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/123928892/223393659-ac8629df-a41d-47c9-997b-afce3eefbf94.png">

expected:
![img_v2_256eabf2-38e8-468a-91d0-b8958e5a4e7g](https://user-images.githubusercontent.com/123928892/223393734-b89fcc36-f23b-4d58-b00c-b868ce44d7d2.jpg)

render with rdkit (expected):
![img_v2_2776c68b-8a27-4d19-9f45-a5d1c48a5ccg](https://user-images.githubusercontent.com/123928892/223393875-7b2bb318-9489-4d4f-8388-a204a9d8ca1a.jpg)

**Comment by mgreiner79** [comment]
If you change 'compactDrawing' parameter to false then I think you should get the expected result. 
```
      let options = {
        compactDrawing: false,
      };
      let smilesDrawer = new SmilesDrawer.Drawer(options);
```

**Comment by Valen-C12** [comment]
> If you change 'compactDrawing' parameter to false then I think you should get the expected result.
> 
> ```
>       let options = {
>         compactDrawing: false,
>       };
>       let smilesDrawer = new SmilesDrawer.Drawer(options);
> ```

This is correct, thanks for the tip
