### ISSUE TITLE
padding

### ISSUE THREAD

**Issue by durrantlab** [reymond-group/smilesDrawer#71]
Thanks for the great library. Just wanted to let you know that, though one of the listed options for your SmilesDrawer object is "padding," that value is in fact hardcoded:

`// Add padding
var padding = 5.0;
maxX += padding;
maxY += padding;
minX -= padding;
minY -= padding;`

Would be nice to make it a true user-defined parameter when you get a chance. Thanks again!

**Comment by daenuprobst** [comment]
You are welcome and thank you for your interest. This issue should have been solved with PR #69. Please feel free to reopen the issue if the problem persists.
