### ISSUE TITLE
lots of overlapping 

### ISSUE THREAD

**Issue by A-Thakkar** [reymond-group/smilesDrawer#74]
Smiles:
C=C1C[C@@H]2CC[C@@]34C[C@H]5O[C@H]6[C@@H](O3)[C@H]3OC(CC[C@@H]3O[C@H]6[C@H]5O4)CC(=O)C[C@H]3[C@H](C[C@H]4O[C@@H](CC[C@@H]1O2)C[C@@H](C)C4=C)O[C@H](C[C@H](O)CN)[C@@H]3OC

SmilesDrawer:
![smiles](https://user-images.githubusercontent.com/30608074/44224566-2484a900-a18b-11e8-967f-bbabb76c1070.png)

Marvin:
![marvin_smiles](https://user-images.githubusercontent.com/30608074/44224620-48e08580-a18b-11e8-8f69-3fa4c87027ce.png)

**Comment by daenuprobst** [comment]
Should be fixed now with `experimentalSSSR: true`.
